
const TABLE_SCHEMA = `
create table public.sensor_data (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  temperature real null,
  humidity real null,
  moisture integer null,
  light integer null,
  rain boolean null,
  constraint sensor_data_pkey primary key (id)
) TABLESPACE pg_default;

create table public.plant_health_analyses (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  user_id uuid null,
  image_url text null,
  result jsonb null,
  constraint plant_health_analyses_pkey primary key (id),
  constraint plant_health_analyses_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;
`;

export async function getTableSchema(): Promise<string> {
  return TABLE_SCHEMA;
}
